apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: all
        labels:
          app.kubernetes.io/instance: flux-system
      spec:
        template:
          spec:
            securityContext:
              fsGroup: 1337
              $patch: delete
    target:
      kind: Deployment